version: '3'
services:
  salt:
    hostname: salt-master
    build:
      context: ./docker-salt-master/
    ports:
     - "4505:4505"
     - "4506:4506"
     - "444:443"
     - "8010:8000"
    volumes:
      - ./salt/master.d:/etc/salt/master.d
      - ./salt/profiles:/srv/salt
      - ./salt/pillars:/srv/pillar

  haproxy:
    hostname: haproxy
    build:
      context: ./haproxy/
    ports:
     - "80:80"
     - "1936:1936"
    volumes:
      # - ./minion-bootstrap.sh:/minion-bootstrap.sh
      - ./salt/minion:/etc/salt/minion
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

  service_a:
    hostname: service-a
    build:
      context: ./web/
    ports:
     - "8001:80"
    volumes:
      #- ./bootstrap-salt.sh:/bootstrap-salt.sh
      - ./salt/minion:/etc/salt/minion
      - ./web/service-a.html:/usr/share/nginx/html/index.html

  service_a_1:
    hostname: service-a-1
    build:
      context: ./web/
    ports:
     - "8003:80"
    volumes:
      #- ./bootstrap-salt.sh:/bootstrap-salt.sh
      - ./salt/minion:/etc/salt/minion
      - ./web/service-a.html:/usr/share/nginx/html/index.html

  service_b:
    hostname: service-b
    build:
      context: ./web/
    ports:
     - "8002:80"
    volumes:
      #- ./bootstrap-salt.sh:/bootstrap-salt.sh
      - ./salt/minion:/etc/salt/minion
      - ./web/service-a.html:/usr/share/nginx/html/index.html

  service_b_1:
    hostname: service-b-1
    build:
      context: ./web/
    ports:
     - "8004:80"
    volumes:
      #- ./bootstrap-salt.sh:/bootstrap-salt.sh
      - ./salt/minion:/etc/salt/minion
      - ./web/service-a.html:/usr/share/nginx/html/index.html